/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuardedRouteImport } from './routes/_guarded'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as GuardedPlayRouteImport } from './routes/_guarded/play'
import { Route as GuardedCatIdRouteImport } from './routes/_guarded/$catId'
import { Route as publicTocRouteImport } from './routes/(public)/toc'
import { Route as publicPpRouteImport } from './routes/(public)/pp'
import { Route as publicChronicleRouteImport } from './routes/(public)/chronicle'
import { Route as GuardedCongressIndexRouteImport } from './routes/_guarded/congress/index'
import { Route as GuardedConfigIndexRouteImport } from './routes/_guarded/config/index'
import { Route as GuardedCatSummonRouteImport } from './routes/_guarded/cat/summon'
import { Route as publicAuthSignInRouteImport } from './routes/(public)/auth/sign-in'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthPasswordResetRouteImport } from './routes/(public)/auth/password-reset'
import { Route as GuardedCatIdPlayIndexRouteImport } from './routes/_guarded/$catId/play/index'
import { Route as GuardedCatIdCatStatusRouteImport } from './routes/_guarded/$catId/cat/status'
import { Route as GuardedCatIdCatCareHistoryRouteImport } from './routes/_guarded/$catId/cat/care-history'
import { Route as GuardedCatIdCatPersonalityIndexRouteImport } from './routes/_guarded/$catId/cat/personality/index'
import { Route as GuardedCatIdCatFriendIndexRouteImport } from './routes/_guarded/$catId/cat/friend/index'
import { Route as GuardedCatIdCatPersonalityIntroductionRouteImport } from './routes/_guarded/$catId/cat/personality/introduction'

const GuardedRoute = GuardedRouteImport.update({
  id: '/_guarded',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedPlayRoute = GuardedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatIdRoute = GuardedCatIdRouteImport.update({
  id: '/$catId',
  path: '/$catId',
  getParentRoute: () => GuardedRoute,
} as any)
const publicTocRoute = publicTocRouteImport.update({
  id: '/(public)/toc',
  path: '/toc',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPpRoute = publicPpRouteImport.update({
  id: '/(public)/pp',
  path: '/pp',
  getParentRoute: () => rootRouteImport,
} as any)
const publicChronicleRoute = publicChronicleRouteImport.update({
  id: '/(public)/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedCongressIndexRoute = GuardedCongressIndexRouteImport.update({
  id: '/congress/',
  path: '/congress/',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedConfigIndexRoute = GuardedConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => GuardedRoute,
} as any)
const GuardedCatSummonRoute = GuardedCatSummonRouteImport.update({
  id: '/cat/summon',
  path: '/cat/summon',
  getParentRoute: () => GuardedRoute,
} as any)
const publicAuthSignInRoute = publicAuthSignInRouteImport.update({
  id: '/(public)/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/(public)/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthPasswordResetRoute = publicAuthPasswordResetRouteImport.update({
  id: '/(public)/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardedCatIdPlayIndexRoute = GuardedCatIdPlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => GuardedCatIdRoute,
} as any)
const GuardedCatIdCatStatusRoute = GuardedCatIdCatStatusRouteImport.update({
  id: '/cat/status',
  path: '/cat/status',
  getParentRoute: () => GuardedCatIdRoute,
} as any)
const GuardedCatIdCatCareHistoryRoute =
  GuardedCatIdCatCareHistoryRouteImport.update({
    id: '/cat/care-history',
    path: '/cat/care-history',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)
const GuardedCatIdCatPersonalityIndexRoute =
  GuardedCatIdCatPersonalityIndexRouteImport.update({
    id: '/cat/personality/',
    path: '/cat/personality/',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)
const GuardedCatIdCatFriendIndexRoute =
  GuardedCatIdCatFriendIndexRouteImport.update({
    id: '/cat/friend/',
    path: '/cat/friend/',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)
const GuardedCatIdCatPersonalityIntroductionRoute =
  GuardedCatIdCatPersonalityIntroductionRouteImport.update({
    id: '/cat/personality/introduction',
    path: '/cat/personality/introduction',
    getParentRoute: () => GuardedCatIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/chronicle': typeof publicChronicleRoute
  '/pp': typeof publicPpRoute
  '/toc': typeof publicTocRoute
  '/$catId': typeof GuardedCatIdRouteWithChildren
  '/play': typeof GuardedPlayRoute
  '/auth/password-reset': typeof publicAuthPasswordResetRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/auth/sign-in': typeof publicAuthSignInRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/config/': typeof GuardedConfigIndexRoute
  '/congress/': typeof GuardedCongressIndexRoute
  '/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/$catId/play/': typeof GuardedCatIdPlayIndexRoute
  '/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/$catId/cat/friend/': typeof GuardedCatIdCatFriendIndexRoute
  '/$catId/cat/personality/': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/chronicle': typeof publicChronicleRoute
  '/pp': typeof publicPpRoute
  '/toc': typeof publicTocRoute
  '/$catId': typeof GuardedCatIdRouteWithChildren
  '/play': typeof GuardedPlayRoute
  '/auth/password-reset': typeof publicAuthPasswordResetRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/auth/sign-in': typeof publicAuthSignInRoute
  '/cat/summon': typeof GuardedCatSummonRoute
  '/config': typeof GuardedConfigIndexRoute
  '/congress': typeof GuardedCongressIndexRoute
  '/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/$catId/play': typeof GuardedCatIdPlayIndexRoute
  '/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/$catId/cat/friend': typeof GuardedCatIdCatFriendIndexRoute
  '/$catId/cat/personality': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guarded': typeof GuardedRouteWithChildren
  '/(public)/chronicle': typeof publicChronicleRoute
  '/(public)/pp': typeof publicPpRoute
  '/(public)/toc': typeof publicTocRoute
  '/_guarded/$catId': typeof GuardedCatIdRouteWithChildren
  '/_guarded/play': typeof GuardedPlayRoute
  '/(public)/': typeof publicIndexRoute
  '/(public)/auth/password-reset': typeof publicAuthPasswordResetRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(public)/auth/sign-in': typeof publicAuthSignInRoute
  '/_guarded/cat/summon': typeof GuardedCatSummonRoute
  '/_guarded/config/': typeof GuardedConfigIndexRoute
  '/_guarded/congress/': typeof GuardedCongressIndexRoute
  '/_guarded/$catId/cat/care-history': typeof GuardedCatIdCatCareHistoryRoute
  '/_guarded/$catId/cat/status': typeof GuardedCatIdCatStatusRoute
  '/_guarded/$catId/play/': typeof GuardedCatIdPlayIndexRoute
  '/_guarded/$catId/cat/personality/introduction': typeof GuardedCatIdCatPersonalityIntroductionRoute
  '/_guarded/$catId/cat/friend/': typeof GuardedCatIdCatFriendIndexRoute
  '/_guarded/$catId/cat/personality/': typeof GuardedCatIdCatPersonalityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chronicle'
    | '/pp'
    | '/toc'
    | '/$catId'
    | '/play'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/summon'
    | '/config/'
    | '/congress/'
    | '/$catId/cat/care-history'
    | '/$catId/cat/status'
    | '/$catId/play/'
    | '/$catId/cat/personality/introduction'
    | '/$catId/cat/friend/'
    | '/$catId/cat/personality/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chronicle'
    | '/pp'
    | '/toc'
    | '/$catId'
    | '/play'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/cat/summon'
    | '/config'
    | '/congress'
    | '/$catId/cat/care-history'
    | '/$catId/cat/status'
    | '/$catId/play'
    | '/$catId/cat/personality/introduction'
    | '/$catId/cat/friend'
    | '/$catId/cat/personality'
  id:
    | '__root__'
    | '/_guarded'
    | '/(public)/chronicle'
    | '/(public)/pp'
    | '/(public)/toc'
    | '/_guarded/$catId'
    | '/_guarded/play'
    | '/(public)/'
    | '/(public)/auth/password-reset'
    | '/(public)/auth/register'
    | '/(public)/auth/sign-in'
    | '/_guarded/cat/summon'
    | '/_guarded/config/'
    | '/_guarded/congress/'
    | '/_guarded/$catId/cat/care-history'
    | '/_guarded/$catId/cat/status'
    | '/_guarded/$catId/play/'
    | '/_guarded/$catId/cat/personality/introduction'
    | '/_guarded/$catId/cat/friend/'
    | '/_guarded/$catId/cat/personality/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuardedRoute: typeof GuardedRouteWithChildren
  publicChronicleRoute: typeof publicChronicleRoute
  publicPpRoute: typeof publicPpRoute
  publicTocRoute: typeof publicTocRoute
  publicIndexRoute: typeof publicIndexRoute
  publicAuthPasswordResetRoute: typeof publicAuthPasswordResetRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
  publicAuthSignInRoute: typeof publicAuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guarded': {
      id: '/_guarded'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuardedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded/play': {
      id: '/_guarded/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof GuardedPlayRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/$catId': {
      id: '/_guarded/$catId'
      path: '/$catId'
      fullPath: '/$catId'
      preLoaderRoute: typeof GuardedCatIdRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/(public)/toc': {
      id: '/(public)/toc'
      path: '/toc'
      fullPath: '/toc'
      preLoaderRoute: typeof publicTocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/pp': {
      id: '/(public)/pp'
      path: '/pp'
      fullPath: '/pp'
      preLoaderRoute: typeof publicPpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/chronicle': {
      id: '/(public)/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof publicChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded/congress/': {
      id: '/_guarded/congress/'
      path: '/congress'
      fullPath: '/congress/'
      preLoaderRoute: typeof GuardedCongressIndexRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/config/': {
      id: '/_guarded/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof GuardedConfigIndexRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/_guarded/cat/summon': {
      id: '/_guarded/cat/summon'
      path: '/cat/summon'
      fullPath: '/cat/summon'
      preLoaderRoute: typeof GuardedCatSummonRouteImport
      parentRoute: typeof GuardedRoute
    }
    '/(public)/auth/sign-in': {
      id: '/(public)/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof publicAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/password-reset': {
      id: '/(public)/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof publicAuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guarded/$catId/play/': {
      id: '/_guarded/$catId/play/'
      path: '/play'
      fullPath: '/$catId/play/'
      preLoaderRoute: typeof GuardedCatIdPlayIndexRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/status': {
      id: '/_guarded/$catId/cat/status'
      path: '/cat/status'
      fullPath: '/$catId/cat/status'
      preLoaderRoute: typeof GuardedCatIdCatStatusRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/care-history': {
      id: '/_guarded/$catId/cat/care-history'
      path: '/cat/care-history'
      fullPath: '/$catId/cat/care-history'
      preLoaderRoute: typeof GuardedCatIdCatCareHistoryRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/personality/': {
      id: '/_guarded/$catId/cat/personality/'
      path: '/cat/personality'
      fullPath: '/$catId/cat/personality/'
      preLoaderRoute: typeof GuardedCatIdCatPersonalityIndexRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/friend/': {
      id: '/_guarded/$catId/cat/friend/'
      path: '/cat/friend'
      fullPath: '/$catId/cat/friend/'
      preLoaderRoute: typeof GuardedCatIdCatFriendIndexRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
    '/_guarded/$catId/cat/personality/introduction': {
      id: '/_guarded/$catId/cat/personality/introduction'
      path: '/cat/personality/introduction'
      fullPath: '/$catId/cat/personality/introduction'
      preLoaderRoute: typeof GuardedCatIdCatPersonalityIntroductionRouteImport
      parentRoute: typeof GuardedCatIdRoute
    }
  }
}

interface GuardedCatIdRouteChildren {
  GuardedCatIdCatCareHistoryRoute: typeof GuardedCatIdCatCareHistoryRoute
  GuardedCatIdCatStatusRoute: typeof GuardedCatIdCatStatusRoute
  GuardedCatIdPlayIndexRoute: typeof GuardedCatIdPlayIndexRoute
  GuardedCatIdCatPersonalityIntroductionRoute: typeof GuardedCatIdCatPersonalityIntroductionRoute
  GuardedCatIdCatFriendIndexRoute: typeof GuardedCatIdCatFriendIndexRoute
  GuardedCatIdCatPersonalityIndexRoute: typeof GuardedCatIdCatPersonalityIndexRoute
}

const GuardedCatIdRouteChildren: GuardedCatIdRouteChildren = {
  GuardedCatIdCatCareHistoryRoute: GuardedCatIdCatCareHistoryRoute,
  GuardedCatIdCatStatusRoute: GuardedCatIdCatStatusRoute,
  GuardedCatIdPlayIndexRoute: GuardedCatIdPlayIndexRoute,
  GuardedCatIdCatPersonalityIntroductionRoute:
    GuardedCatIdCatPersonalityIntroductionRoute,
  GuardedCatIdCatFriendIndexRoute: GuardedCatIdCatFriendIndexRoute,
  GuardedCatIdCatPersonalityIndexRoute: GuardedCatIdCatPersonalityIndexRoute,
}

const GuardedCatIdRouteWithChildren = GuardedCatIdRoute._addFileChildren(
  GuardedCatIdRouteChildren,
)

interface GuardedRouteChildren {
  GuardedCatIdRoute: typeof GuardedCatIdRouteWithChildren
  GuardedPlayRoute: typeof GuardedPlayRoute
  GuardedCatSummonRoute: typeof GuardedCatSummonRoute
  GuardedConfigIndexRoute: typeof GuardedConfigIndexRoute
  GuardedCongressIndexRoute: typeof GuardedCongressIndexRoute
}

const GuardedRouteChildren: GuardedRouteChildren = {
  GuardedCatIdRoute: GuardedCatIdRouteWithChildren,
  GuardedPlayRoute: GuardedPlayRoute,
  GuardedCatSummonRoute: GuardedCatSummonRoute,
  GuardedConfigIndexRoute: GuardedConfigIndexRoute,
  GuardedCongressIndexRoute: GuardedCongressIndexRoute,
}

const GuardedRouteWithChildren =
  GuardedRoute._addFileChildren(GuardedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuardedRoute: GuardedRouteWithChildren,
  publicChronicleRoute: publicChronicleRoute,
  publicPpRoute: publicPpRoute,
  publicTocRoute: publicTocRoute,
  publicIndexRoute: publicIndexRoute,
  publicAuthPasswordResetRoute: publicAuthPasswordResetRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
  publicAuthSignInRoute: publicAuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
