/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TocRouteImport } from './routes/toc'
import { Route as PpRouteImport } from './routes/pp'
import { Route as PlayIndexRouteImport } from './routes/play/index'
import { Route as gateIndexRouteImport } from './routes/(gate)/index'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthPasswordResetRouteImport } from './routes/auth/password-reset'

const TocRoute = TocRouteImport.update({
  id: '/toc',
  path: '/toc',
  getParentRoute: () => rootRouteImport,
} as any)
const PpRoute = PpRouteImport.update({
  id: '/pp',
  path: '/pp',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const gateIndexRoute = gateIndexRouteImport.update({
  id: '/(gate)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordResetRoute = AuthPasswordResetRouteImport.update({
  id: '/auth/password-reset',
  path: '/auth/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof gateIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRoutesByTo {
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/': typeof gateIndexRoute
  '/play': typeof PlayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/pp': typeof PpRoute
  '/toc': typeof TocRoute
  '/auth/password-reset': typeof AuthPasswordResetRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/(gate)/': typeof gateIndexRoute
  '/play/': typeof PlayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/'
    | '/play/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/'
    | '/play'
  id:
    | '__root__'
    | '/pp'
    | '/toc'
    | '/auth/password-reset'
    | '/auth/register'
    | '/auth/sign-in'
    | '/(gate)/'
    | '/play/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PpRoute: typeof PpRoute
  TocRoute: typeof TocRoute
  AuthPasswordResetRoute: typeof AuthPasswordResetRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSignInRoute: typeof AuthSignInRoute
  gateIndexRoute: typeof gateIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toc': {
      id: '/toc'
      path: '/toc'
      fullPath: '/toc'
      preLoaderRoute: typeof TocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pp': {
      id: '/pp'
      path: '/pp'
      fullPath: '/pp'
      preLoaderRoute: typeof PpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(gate)/': {
      id: '/(gate)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof gateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password-reset': {
      id: '/auth/password-reset'
      path: '/auth/password-reset'
      fullPath: '/auth/password-reset'
      preLoaderRoute: typeof AuthPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PpRoute: PpRoute,
  TocRoute: TocRoute,
  AuthPasswordResetRoute: AuthPasswordResetRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSignInRoute: AuthSignInRoute,
  gateIndexRoute: gateIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
