export enum ConsensusValueType {
  STRING = "STRING",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
}

export const CONSENSUS_DEFINITIONS = {
  "CAT.COOLDOWN_HOUR_BETWEEN_CARE": ConsensusValueType.NUMBER,
  "CAT.GROWTH_PER_CARE": ConsensusValueType.NUMBER,
  "CAT.EMOTION_PER_CARE": ConsensusValueType.NUMBER,
  "CAT.EMOTION_DECREASE": ConsensusValueType.NUMBER,
  "CAT.EMOTION_DECREASE_FREQUENCY_HOUR": ConsensusValueType.NUMBER,
  "RELATIONSHIP.UNFRIENDED_SCORE_PENALTY": ConsensusValueType.NUMBER,
  "RELATIONSHIP.FRIEND_MATCH_PROBABILITY": ConsensusValueType.NUMBER,
  "RELATIONSHIP.LOVE_MATCH_PROBABILITY_DIFF_SEX": ConsensusValueType.NUMBER,
  "RELATIONSHIP.LOVE_MATCH_PROBABILITY_SAME_SEX": ConsensusValueType.NUMBER,
} as const;

export type ConsensusKey = keyof typeof CONSENSUS_DEFINITIONS;
